source_identifier: ""
skip_incomplete_events: false

event_source:
    type: InternalEventSource
    number_of_events_to_generate: 76

data_sources:
    random_example1:
        type: GenericRandomNumpyArray
        array_shape: 20,2
        array_dtype: float32
        always_random: True
    random_example2:
        type: GenericRandomNumpyArray
        array_shape: 3,
        array_dtype: uint16
        always_random: False
    const_data_example1:
        type: ConstValue
        value: 6.4
        dtype: float64
    const_data_example2:
        type: ConstValue
        value: [6, 3, 1]
        dtype: uint32

processing_pipeline:
    type: BatchProcessingPipeline
    batch_size: 2

data_serializer:
    type: HDF5BinarySerializer
    compression_level: 3
    compression: null
    #fields:
    #    random: /data/random
    #    int: /data/int
    #    float: /data/float

data_handlers:
    #    - type: BinaryFileWritingDataHandler
    #      file_prefix: ""
    #      file_suffix: h5
    #      write_directory: workspace/output
    - type: BinaryDataStreamingDataHandler
      urls:
          - "tcp://127.0.0.1:12321"
      role: client
      library: zmq
      socket_type: push
